version: '3'
services:
  my_app:
    #build: .
    image: javeedmlv/my_app:1.0
    ports:
      - 3000:3000
    environment:
      - MONGO_DB_USERNAME=${MONGO_USER}
      - MONGO_DB_PWD=${MONGO_PWD}
  
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PWD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"